version: '3.8'

services:
  mariadb:
    image: mariadb:10.2
    container_name: mariadb
    env_file:
      - ./database/.env
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./database/conf.d:/etc/mysql/conf.d
      - ./database/initd.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    entrypoint: ["sh", "-c", "chown -R mysql:mysql /var/lib/mysql && chmod 644 /etc/mysql/conf.d/*.cnf && docker-entrypoint.sh mysqld"]
    restart: always

  server:
    image: devdiver/vacation_promotion_server:latest
    container_name: vacation_promotion_server
    depends_on:
      - mariadb
      - client
    volumes:
      - ./config:/app/backend/config
      - ./database:/app/backend/database
      - front_app:/app/dist
    ports:
      - "3000:3000"
    env_file:
      - ./database/.env
    restart: always

  client:
    image: devdiver/vacation_promotion_client:latest
    container_name: vacation_promotion_client
    volumes:
      - front_app:/dist
    command: ["sh", "-c", "rm -rf /dist/* && mv /app/front_web/dist/* /dist && bin/true"]

  webhook-server:
    image: devdiver/webhook:latest
    container_name: webhook_server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "5000:5000"
    restart: always

volumes:
  mariadb_data:
  front_app: