version: '3.8'

services:
  mariadb:
    image: mariadb:10.2
    container_name: mariadb
    env_file:
      - ./database/.env
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./database/conf.d:/etc/mysql/conf.d
      - ./database/initd.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    command: ["sh", "-c", "
      # 볼륨 마운트 기다리기
      while [ ! -f /etc/mysql/conf.d/*.cnf ]; do
        echo 'Waiting for volume to be mounted...'
        sleep 2
      done

      # 초기화 작업
      chown -R mysql:mysql /var/lib/mysql
      chmod 644 /etc/mysql/conf.d/*.cnf || true

      # 기본 엔트리포인트 실행
      exec docker-entrypoint.sh mysqld"]
    restart: always

  server:
    image: devdiver/vacation_promotion_server:latest
    container_name: vacation_promotion_server
    depends_on:
      - mariadb
      - client
    volumes:
      - ./config:/app/backend/config
      - ./database:/app/backend/database
      - front_app:/app/dist
    ports:
      - "3000:3000"
    env_file:
      - ./database/.env
    restart: always

  client:
    image: devdiver/vacation_promotion_client:latest
    container_name: vacation_promotion_client
    volumes:
      - front_app:/dist
    command: ["sh", "-c", "rm -rf /dist/* && mv /app/front_web/dist/* /dist && bin/true"]

  webhook-server:
    image: devdiver/webhook:latest
    container_name: webhook_server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./database/conf.d:/etc/mysql/conf.d
      - ./database:/vps_central/database
      - ./config:/vps_central/config
    ports:
      - "5000:5000"
    restart: always

volumes:
  mariadb_data:
  front_app: