networks:
  net:
    driver: bridge
services:
  mariadb:
    image: mariadb:10.2
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_USER}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - DATABASE_HOST=mariadb
      - DATABASE_USER=${DB_USER}
      - DATABASE_PASSWORD=${DB_PASS}
      - DATABASE_NAME=${DB_NAME}
      - DATABASE_PORT=${DB_PORT}
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./database/conf.d:/etc/mysql/conf.d
      - ./database/initd.d:/docker-entrypoint-initdb.d
    ports:
      - "3307:${DB_PORT}"
    networks:
      - net
    entrypoint: ["sh", "-c", "chown -R mysql:mysql /var/lib/mysql && chmod 644 /etc/mysql/conf.d/*.cnf && docker-entrypoint.sh mysqld"]
    restart: always

  server:
    build: 
      context: ../VPS_backend
    container_name: server
    env_file:
      - .env
    volumes:
      - front_app:/dist
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3000:3000"
    networks:
      - net
    restart: always
    privileged: true

  client:
    build: 
      context: ../VPS_client
    container_name: client
    volumes:
      - front_app:/dist
    command: ["sh", "-c", "rm -rf /dist/* && mv /app/front_web/dist/* /dist"]

  update-server:
    build: .
    container_name: update-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "5000:5000"
    networks:
      - net
    restart: always

volumes:
  mariadb_data:
  front_app:
