version: '3.8'

services:
  mariadb:
    image: mariadb:10.2
    container_name: mariadb
    env_file:
      - ./database/.env
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./database/conf.d:/etc/mysql/conf.d
      - ./database/initd.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    entrypoint: ["sh", "-c", "chown -R mysql:mysql /var/lib/mysql && chmod 644 /etc/mysql/conf.d/*.cnf && docker-entrypoint.sh mysqld"]
    restart: always

  server:
    image: devdiver/vacation_promotion_server:latest
    container_name: vacation_promotion_server
    # environment:
    #   - HOST_IP=${HOST_IP}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKER}:/usr/bin/docker
      - ${DOCKER_COMPOSE}:/usr/bin/docker-compose
      - config:/app/backend/config
      - database:/app/backend/database
      - front_app:/app/dist
      - /docker-compose.yml:/app/backend/docker-compose.yml
    ports:
      - "3000:3000"
    restart: always
    privileged: true

  client:
    image: devdiver/vacation_promotion_client:latest
    container_name: vacation_promotion_client
    volumes:
      - front_app:/dist
    command: ["sh", "-c", "rm -rf /dist/* && mv /app/front_web/dist/* /dist && bin/true"]

  # webhook-server:
  #   image: devdiver/webhook:latest
  #   container_name: webhook_server
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - ./database/conf.d:/etc/mysql/conf.d
  #     - config:/vps_central/config
  #     - database:/vps_central/database
  #   ports:
  #     - "5000:5000"
  #   restart: always

volumes:
  mariadb_data:
  front_app:
  database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./database
  config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./config